# =============================================================
# docker-compose.yml — Freesia MODULE_Worker
# =============================================================

version: "3.9"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: freesia/module-worker:1.0.5
    container_name: freesia-worker
    restart: unless-stopped
    tty: true
    stdin_open: true
    
    networks:
      - freesia-network

    ports:
      - "${MC_PORT:-19199}:19199"

    env_file:
      - .env

    volumes:
      - ./.fabric:/server/.fabric
      - ./config:/server/config
      - ./libraries:/server/libraries
      - ./logs:/server/logs
      - ./mods:/server/mods
      - ./versions:/server/versions
      - ./world:/server/world
      - ./crash-reports:/server/crash-reports
      - ./usercache.json:/server/usercache.json
      - ./ops.json:/server/ops.json
      - ./whitelist.json:/server/whitelist.json
      - ./banned-players.json:/server/banned-players.json
      - ./banned-ips.json:/server/banned-ips.json
      - ./server.properties:/server/server.properties
      - ./mounts.json:/server/mounts.json
      - ./freesia_node_info.bin:/server/freesia_node_info.bin

networks:
  freesia-network:
    external: true