# =============================================================
# docker-compose.yml — Freesia SUB_Lobby
# =============================================================

version: "3.9"

services:
  sub-lobby:
    build:
      context: .
      dockerfile: Dockerfile
    image: freesia/sub-lobby:1.0.0
    container_name: freesia-sub-lobby
    restart: unless-stopped
    tty: true
    stdin_open: true
    
    networks:
      - freesia-network

    ports:
      - "${MC_PORT:-25566}:25566"

    env_file:
      - .env

    volumes:
      - ./cache:/server/cache
      - ./config:/server/config
      - ./libraries:/server/libraries
      - ./logs:/server/logs
      - ./world:/server/world
      - ./lobby:/server/lobby
      - ./plugins:/server/plugins
      - ./versions:/server/versions
      - ./banned-ips.json:/server/banned-ips.json
      - ./banned-players.json:/server/banned-players.json
      - ./bukkit.yml:/server/bukkit.yml
      - ./commands.yml:/server/commands.yml
      - ./ops.json:/server/ops.json
      - ./spigot.yml:/server/spigot.yml
      - ./usercache.json:/server/usercache.json
      - ./whitelist.json:/server/whitelist.json
      - ./server.properties:/server/server.properties
      - ./help.yml:/server/help.yml
      - ./permissions.yml:/server/permissions.yml
      - ./wepif.yml:/server/wepif.yml

networks:
  freesia-network:
    external: true
